In [1]:
import pandas as pd
import sqlalchemy
import csv

In [2]:
engine = sqlalchemy.create_engine('mysql+pymysql://siorf:PMseis06@mysql.siorf.kinghost.net:3306/siorf')

In [3]:
#Preciso remover o id_Proposta da tabela Proposta Setorial e inserir o Código do Cadastro de Demandas do Banco em mysql
#preciso remover as colunas de priorização pois com os planos diretores priorizados o banco não terá a priorização na proposta
#e remover a priorização (melhor criar uma uma tabela temporária no banco pois a priorização do Plano diretor também é local)

In [4]:
#Primeiro abro a tbl_PropostaSetorial.csv etraida do acces e tranformo em df, importante lembrar que é necessário identificar o delimitador
# Salvo o resultado em uma variável
dfProposta = pd.read_csv('tbl_PropostasSetoriais2021.csv', delimiter = ';')
dfProposta

,Id_PropostaSetorial2021,pps_CodigoDemanda,pps_Justificativa,pps_AlinhamentoEstrategico,pps_Quantidade,pps_Valor,pps_Gravidade,pps_Tendencia,pps_Urgencia,pps_Observacao,pps_UnidadeDemandante,pps_Exercício
0,36,1,LEI N° 10.486/2002 E LEI N° 12.086/2022,1.2.1,126648.0,"34843636,2",5.0,5.0,5.0,NaN,DPPP,2021
1,18,2,LEI N° 840/2018/DECRETO 40.610/2030,1.2.1,370.0,"18997202,16",5.0,5.0,5.0,NaN,DPPP,2021
2,37,3,LEI N° 10.486/2002 E LEI N° 12.086/2023,1.2.1,126648.0,"4421741,52",5.0,5.0,5.0,NaN,DPPP,2021
3,38,4,LEI N° 10.486/2002 E LEI N° 12.086/2024,1.2.1,126648.0,"446097878,8",5.0,5.0,5.0,NaN,DPPP,2021
4,39,5,LEI N° 10.486/2002 E LEI N° 12.086/2025,1.2.1,126648.0,"240697190,8",5.0,5.0,5.0,NaN,DPPP,2021
...,...,...,...,...,...,...,...,...,...,...,...,...
312,313,365,NaN,NaN,NaN,1200000,NaN,NaN,NaN,NaN,NaN,2021
313,314,366,NaN,NaN,NaN,3970000,NaN,NaN,NaN,NaN,NaN,2021
314,315,367,NaN,NaN,NaN,501200,NaN,NaN,NaN,NaN,NaN,2021
315,316,368,NaN,NaN,NaN,"2421586,93",NaN,NaN,NaN,NaN,NaN,2021
316,317,369,NaN,NaN,NaN,100000,NaN,NaN,NaN,NaN,NaN,2021

In [5]:
#Preciso remover o id_Proposta da tabaela Proposta Setorial e inserir o Código do Cadastro de Demandas do Banco em mysql
#e remover a priorização (melhor criar uma uma tabela temporária no banco pois a priorização do Plano diretor também é local)

dfPropostaLimpa = dfProposta.drop(columns=['Id_PropostaSetorial2021', 'pps_Gravidade','pps_Tendencia', 'pps_Urgencia'])
dfPropostaLimpa

,pps_CodigoDemanda,pps_Justificativa,pps_AlinhamentoEstrategico,pps_Quantidade,pps_Valor,pps_Observacao,pps_UnidadeDemandante,pps_Exercício
0,1,LEI N° 10.486/2002 E LEI N° 12.086/2022,1.2.1,126648.0,"34843636,2",NaN,DPPP,2021
1,2,LEI N° 840/2018/DECRETO 40.610/2030,1.2.1,370.0,"18997202,16",NaN,DPPP,2021
2,3,LEI N° 10.486/2002 E LEI N° 12.086/2023,1.2.1,126648.0,"4421741,52",NaN,DPPP,2021
3,4,LEI N° 10.486/2002 E LEI N° 12.086/2024,1.2.1,126648.0,"446097878,8",NaN,DPPP,2021
4,5,LEI N° 10.486/2002 E LEI N° 12.086/2025,1.2.1,126648.0,"240697190,8",NaN,DPPP,2021
...,...,...,...,...,...,...,...,...
312,365,NaN,NaN,NaN,1200000,NaN,NaN,2021
313,366,NaN,NaN,NaN,3970000,NaN,NaN,2021
314,367,NaN,NaN,NaN,501200,NaN,NaN,2021
315,368,NaN,NaN,NaN,"2421586,93",NaN,NaN,2021
316,369,NaN,NaN,NaN,100000,NaN,NaN,2021

In [6]:
# Foi verificado que existem dois registros de diárias na Tabela Proposta Setorial e na tabela Cadstro.
# A duplicidade da tabela cadastro não pode permanecer.
# A tabela Cadastro já está inserida no Banco então o registro foi invalidade para reutilização futura

In [7]:
#Abro o Cadastro com o id a ser recuperado e armazeno em uma variável
dfCadastro = pd.read_sql_table('tbl_CadastroDemandas',engine)
dfCadastro

,Id_CadastroDemandas,cad_CodigoDemanda,cad_CoordenadorSetorial,cad_Descricao,cad_FCDFDespesaDetalhada,cad_GDFDespesaDetalhada,cad_ProdutoUnidade,cad_Periodicidade,cad_EspecieDisponibilidade,cad_Observacao,cad_DataInclusao
0,1,174,CCS,Aquisição de medalhas,33903105,,0.0,1.0,5.0,None,NaT
1,2,181,DOP,Taxas Anac,33904710,,0.0,1.0,1.0,None,NaT
2,3,182,DOP,Abastecimento de aeronaves,33903002,,0.0,1.0,1.0,None,NaT
3,4,183,DOP,Seguro das aeronaves da PMDF,33903969,,0.0,1.0,2.0,None,NaT
4,5,184,DOP,Alimentos para animais,33903006,,0.0,1.0,1.0,None,NaT
...,...,...,...,...,...,...,...,...,...,...,...
312,313,296,DINFRA,Pagamento de Taxas CREA/DF,33904710,,449.0,0.0,0.0,None,NaT
313,314,316,DITEL,Métrica e Mensuração de Software em regime de ...,33904015,,449.0,0.0,0.0,None,NaT
314,315,317,DITEL,Fábrica de software - contratação de empresa e...,33904008,,449.0,0.0,0.0,None,NaT
315,316,314,DITEL,CONTRATO - Link de internet - contratação de l...,33903958,,450.0,0.0,0.0,None,NaT
316,317,90,DPGC,Serviço de Gestão hospitalar/ Engenharia Clínica,33903905,,502.0,0.0,5.0,None,NaT

In [8]:
#Selecionar apenas as colunas que serão utilizadas para fazera correspondência entre a tabela Cadastro e a tabela proposta
colunaIdCadastro = dfCadastro[['Id_CadastroDemandas', 'cad_CodigoDemanda']]
colunaIdCadastro

     Id_CadastroDemandas  cad_CodigoDemanda
0                      1                174
1                      2                181
2                      3                182
3                      4                183
4                      5                184
..                   ...                ...
312                  313                296
313                  314                316
314                  315                317
315                  316                314
316                  317                 90

[317 rows x 2 columns]

In [9]:
# Foi atribuído o Id_do Cadastro da demanda na Proposta Setorial
pd.merge(colunaIdCadastro, dfPropostaLimpa, left_on = "cad_CodigoDemanda", right_on = "pps_CodigoDemanda", how = "right" )

,Id_CadastroDemandas,cad_CodigoDemanda,pps_CodigoDemanda,pps_Justificativa,pps_AlinhamentoEstrategico,pps_Quantidade,pps_Valor,pps_Observacao,pps_UnidadeDemandante,pps_Exercício
0,241,1,1,LEI N° 10.486/2002 E LEI N° 12.086/2022,1.2.1,126648.0,"34843636,2",NaN,DPPP,2021
1,223,2,2,LEI N° 840/2018/DECRETO 40.610/2030,1.2.1,370.0,"18997202,16",NaN,DPPP,2021
2,242,3,3,LEI N° 10.486/2002 E LEI N° 12.086/2023,1.2.1,126648.0,"4421741,52",NaN,DPPP,2021
3,243,4,4,LEI N° 10.486/2002 E LEI N° 12.086/2024,1.2.1,126648.0,"446097878,8",NaN,DPPP,2021
4,244,5,5,LEI N° 10.486/2002 E LEI N° 12.086/2025,1.2.1,126648.0,"240697190,8",NaN,DPPP,2021
...,...,...,...,...,...,...,...,...,...,...
312,104,365,365,NaN,NaN,NaN,1200000,NaN,NaN,2021
313,105,366,366,NaN,NaN,NaN,3970000,NaN,NaN,2021
314,106,367,367,NaN,NaN,NaN,501200,NaN,NaN,2021
315,107,368,368,NaN,NaN,NaN,"2421586,93",NaN,NaN,2021
316,108,369,369,NaN,NaN,NaN,100000,NaN,NaN,2021

In [ ]:
#Verificando se a Proposta esta completa, sobretudo no que tange a demanda de código 61.

In [ ]:
#Agora é necessário remover as Colunas com Código da Demanda.

In [ ]:
#agora tenho que selecionar apenas a coluna Id_cadastroDemandas e inseri-la na dfCadastro na ordem em que se encontra.
dfPropostaPronta = pd.DataFrame(dfPropostaSortidaDemanda, rows = [colunaIdCadastro] )
print(dfPropostaPronta)

In [ ]:
print(tbl_PropostaSetorialPronta)