In [1]:
import pandas as pd
import sqlalchemy
import csv

In [2]:
engine = sqlalchemy.create_engine('mysql+pymysql://siorf:PMseis06@mysql.siorf.kinghost.net:3306/siorf')

In [3]:
#Não foi possível localizar as tabelas que deram origem à Proposta encaminhada à Sutes
#Os planos de aquisição encaminhados não coincidem com a proposta encaminhada à Sutes
#É importante que exista a classificação programática da tbl_FDFProposta, todavia não será possível informar os valores para 2021
#Para fazer uma classificação programática serão utilizadas as tabelas tbl_PropostaSetorial e tbl_Cadastro e Demandas
#Com as tabelas mescladas será possível estabelecer os critérios para definir os programas em que cada demanda se enquadra
Proposta1 = pd.read_sql_table('tbl_PropostaSetorial',engine)
Cadastro = pd.read_sql_table('tbl_CadastroDemandas',engine)
Proposta1.head(3)

,Id_PropostaSetorial,pps_CadastroDemanda,pps_Justificativa,pps_alinhamentoEstrategico,pps_Quantidade,pps_Valor,pps_Observacao,pps_UnidadeDemandante,pps_Exercicio
0,1,241,LEI N° 10.486/2002 E LEI N° 12.086/2022,1.2.1,126648,34843636.0,nan,DPPP,2021
1,2,223,LEI N° 840/2018/DECRETO 40.610/2030,1.2.1,370,18997202.0,nan,DPPP,2021
2,3,242,LEI N° 10.486/2002 E LEI N° 12.086/2023,1.2.1,126648,4421741.0,nan,DPPP,2021

In [4]:
Cadastro.head(3)

,Id_CadastroDemandas,cad_CodigoDemanda,cad_CoordenadorSetorial,cad_Descricao,cad_FCDFDespesaDetalhada,cad_GDFDespesaDetalhada,cad_ProdutoUnidade,cad_Periodicidade,cad_EspecieDisponibilidade,cad_Observacao,cad_DataInclusao
0,1,174,CCS,Aquisição de medalhas,33903105,,0.0,1.0,5.0,None,NaT
1,2,181,DOP,Taxas Anac,33904710,,0.0,1.0,1.0,None,NaT
2,3,182,DOP,Abastecimento de aeronaves,33903002,,0.0,1.0,1.0,None,NaT

In [5]:
Proposta2 = Proposta1.merge(Cadastro, left_on='pps_CadastroDemanda', right_on='Id_CadastroDemandas')

In [6]:
#Comando realizado para verificar se as tabelas mescladas estão corretas (durante a inserção da tabela PropostaSetorial verifiquei a duplicidade)
Proposta2.loc[Proposta2['pps_CadastroDemanda']==198]

,Id_PropostaSetorial,pps_CadastroDemanda,pps_Justificativa,pps_alinhamentoEstrategico,pps_Quantidade,pps_Valor,pps_Observacao,pps_UnidadeDemandante,pps_Exercicio,Id_CadastroDemandas,cad_CodigoDemanda,cad_CoordenadorSetorial,cad_Descricao,cad_FCDFDespesaDetalhada,cad_GDFDespesaDetalhada,cad_ProdutoUnidade,cad_Periodicidade,cad_EspecieDisponibilidade,cad_Observacao,cad_DataInclusao
45,46,198,LEI N° 10.486/2002 E LEI N° 12.086/2032,1.2.1,1800,450000.0,nan,DPPP,2021,198,61,DPP,Diária no País,33901514,33901514,256.0,1.0,1.0,None,NaT
46,47,198,LEI N° 840/2018/DECRETO 40.610/2026,1.2.1,330,100000.0,nan,DPPP,2021,198,61,DPP,Diária no País,33901514,33901514,256.0,1.0,1.0,None,NaT

In [7]:
#Construindo a tbl_FCDFProposta programa por programa
FCDFProposta = Proposta2.set_index('cad_CoordenadorSetorial')

In [8]:
FCDFPropostaDLF1 = FCDFProposta.loc[['CCS','DINFRA','DPTS', 'DCC', 'DEC','DITEL','CI','DOP'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor']]

In [9]:
FCDFPropostaDLF2 =FCDFPropostaDLF1.assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00NR', Subtítulo = '0053')

In [10]:
FCDFPropostaDLF2

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_CoordenadorSetorial,,,,,,,,,
CCS,116,12,20000.0,100,28,845,0903,00NR,0053
CCS,117,6,20000.0,100,28,845,0903,00NR,0053
CCS,118,12,20000.0,100,28,845,0903,00NR,0053
CCS,119,1,150000.0,100,28,845,0903,00NR,0053
CCS,120,1,50000.0,100,28,845,0903,00NR,0053
...,...,...,...,...,...,...,...,...,...
DOP,193,0,40000.0,100,28,845,0903,00NR,0053
DOP,194,0,1200000.0,100,28,845,0903,00NR,0053
DOP,197,6,14000.0,100,28,845,0903,00NR,0053
DOP,202,0,900000.0,100,28,845,0903,00NR,0053
DOP,207,0,900000.0,100,28,845,0903,00NR,0053

In [11]:
#Proposta DSAP
FCDFPropostaDSAP1 = FCDFProposta.loc[['DPGC', 'DAO'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor']]

In [12]:
FCDFPropostaDSAP2 = FCDFPropostaDSAP1.assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00FM', Subtítulo = '0053')

In [13]:
FCDFPropostaDSAP2

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_CoordenadorSetorial,,,,,,,,,
DPGC,57,0,650000.0,100,28,845,0903,00FM,0053
DPGC,59,0,893584.0,100,28,845,0903,00FM,0053
DPGC,60,0,115000.0,100,28,845,0903,00FM,0053
DPGC,61,0,12000.0,100,28,845,0903,00FM,0053
DPGC,62,0,920000.0,100,28,845,0903,00FM,0053
...,...,...,...,...,...,...,...,...,...
DAO,113,0,1800000.0,100,28,845,0903,00FM,0053
DAO,114,0,115000.0,100,28,845,0903,00FM,0053
DAO,115,0,65000.0,100,28,845,0903,00FM,0053
DAO,315,0,501200.0,100,28,845,0903,00FM,0053
DAO,316,0,2421586.0,100,28,845,0903,00FM,0053

In [14]:
FCDFPropostaDPP1 = FCDFProposta.loc[['DPP'], [ 'cad_FCDFDespesaDetalhada','Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor']]

In [15]:
FCDFPropostaDPP2 = FCDFPropostaDPP1.set_index('cad_FCDFDespesaDetalhada')
FCDFPropostaDPP2

                          Id_PropostaSetorial  pps_Quantidade    pps_Valor
cad_FCDFDespesaDetalhada
31900109                                    1          126648   34843636.0
                                            2             370   18997202.0
31900115                                    3          126648    4421741.0
31900117                                    4          126648  446097878.0
31900121                                    5          126648  240697190.0
31900122                                    6          126648  534635935.0
31900123                                    7          126648    5400089.0
31900126                                    8           10554   95281452.0
                                            9            4440    1583100.0
                                           10            4440    2773962.0
31900302                                   11           58704  288339863.0
31900304                                   12            4892   22056646.0
                                           13             184     231163.0
                                           14              84     392786.0
                                           15              84     141753.0
                                           16              84      15442.0
                                           17              84      41405.0
                                           18               7     156925.0
                                           19            4440     662323.0
                                           20             377     220774.0
                                           21            4440    6064770.0
                                           22              84      54600.0
31901201                                   23          144636  230354573.0
31901204                                   24          144636  165917967.0
31901206                                   25          144636   70776531.0
31901208                                   26          144636    1671914.0
                                           27             130     594065.0
31901209                                   28          144636  152517596.0
31901210                                   29          300000  120000000.0
31901211                                   30          144636  527653219.0
                                           31            4440    5589521.0
                                           32             130     156231.0
31901242                                   33            3800   30000000.0
31901243                                   34           12053   89365604.0
31901245                                   35           12053   29318756.0
31901287                                   36          144636   15460731.0
                                           37            4440    1750740.0
31909114                                   38              12       1413.0
31909115                                   39             300     880662.0
31909415                                   40            2300  110000000.0
                                           41              84     150000.0
33900802                                   42             170    1600000.0
33900806                                   43             515    1000000.0
33900810                                   44           42199   14209932.0
                                           45             126     115000.0
33901514                                   46            1800     450000.0
33901514                                   47             330     100000.0
33901516                                   48             900     350000.0
33901901                                   49           12053   24755223.0
33904602                                   50           12053  123421299.0
                                           51            4440    1750740.0
                                           52            4440    1026303.0
33905901                                   53              12      95062.0
33909318                                   54             900   33000000.0
33909319                                   55             375     700000.0
33909320                                   56           22607  433012458.0

In [16]:
FCDFPropostaDPPNR = FCDFPropostaDPP2.loc[['33901514', '33901516', '33901901', '33905901', '31901201', '31901204', '31901206', '31901208', '31901209', '31901211', '31901243', '31901245', '31901287', '31909114', '31909415', '31901210', '31901242'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor' ]]
FCDFPropostaDPPNR

                          Id_PropostaSetorial  pps_Quantidade    pps_Valor
cad_FCDFDespesaDetalhada
33901514                                   46            1800     450000.0
33901514                                   47             330     100000.0
33901516                                   48             900     350000.0
33901901                                   49           12053   24755223.0
33905901                                   53              12      95062.0
31901201                                   23          144636  230354573.0
31901204                                   24          144636  165917967.0
31901206                                   25          144636   70776531.0
31901208                                   26          144636    1671914.0
31901209                                   28          144636  152517596.0
31901211                                   30          144636  527653219.0
31901243                                   34           12053   89365604.0
31901245                                   35           12053   29318756.0
31901287                                   36          144636   15460731.0
31909114                                   38              12       1413.0
31909415                                   40            2300  110000000.0
31901210                                   29          300000  120000000.0
31901242                                   33            3800   30000000.0

In [17]:
FCDFPropostaDPPNR1 = FCDFPropostaDPPNR.assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00NR', Subtítulo = '0053')

In [18]:
FCDFPropostaDPPNR2 = FCDFPropostaDPPNR1.query('Id_PropostaSetorial!=47')
FCDFPropostaDPPNR2

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_FCDFDespesaDetalhada,,,,,,,,,
33901514,46,1800,450000.0,100,28,845,0903,00NR,0053
33901516,48,900,350000.0,100,28,845,0903,00NR,0053
33901901,49,12053,24755223.0,100,28,845,0903,00NR,0053
33905901,53,12,95062.0,100,28,845,0903,00NR,0053
31901201,23,144636,230354573.0,100,28,845,0903,00NR,0053
31901204,24,144636,165917967.0,100,28,845,0903,00NR,0053
31901206,25,144636,70776531.0,100,28,845,0903,00NR,0053
31901208,26,144636,1671914.0,100,28,845,0903,00NR,0053
31901209,28,144636,152517596.0,100,28,845,0903,00NR,0053
31901211,30,144636,527653219.0,100,28,845,0903,00NR,0053
31901243,34,12053,89365604.0,100,28,845,0903,00NR,0053
31901245,35,12053,29318756.0,100,28,845,0903,00NR,0053
31901287,36,144636,15460731.0,100,28,845,0903,00NR,0053
31909114,38,12,1413.0,100,28,845,0903,00NR,0053
31909415,40,2300,110000000.0,100,28,845,0903,00NR,0053
31901210,29,300000,120000000.0,100,28,845,0903,00NR,0053
31901242,33,3800,30000000.0,100,28,845,0903,00NR,0053

In [20]:
FCDFPropostaDPPRS = FCDFPropostaDPP2.loc[['33909318', '33909319', '33909320'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor' ]].assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00RS', Subtítulo = '0053')

In [21]:
FCDFPropostaDPPRS

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_FCDFDespesaDetalhada,,,,,,,,,
33909318,54,900,33000000.0,100,28,845,0903,00RS,0053
33909319,55,375,700000.0,100,28,845,0903,00RS,0053
33909320,56,22607,433012458.0,100,28,845,0903,00RS,0053

In [22]:
FCDFPropostaDPPNS = FCDFPropostaDPP2.loc[['31900109', '31900115', '31900117', '31900121', '31900122', '31900123', '31900126', '31909115'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor' ]].assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00NS', Subtítulo = '0053')

In [23]:
FCDFPropostaDPPNS

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_FCDFDespesaDetalhada,,,,,,,,,
31900109,1,126648,34843636.0,100,28,845,0903,00NS,0053
31900115,3,126648,4421741.0,100,28,845,0903,00NS,0053
31900117,4,126648,446097878.0,100,28,845,0903,00NS,0053
31900121,5,126648,240697190.0,100,28,845,0903,00NS,0053
31900122,6,126648,534635935.0,100,28,845,0903,00NS,0053
31900123,7,126648,5400089.0,100,28,845,0903,00NS,0053
31900126,8,10554,95281452.0,100,28,845,0903,00NS,0053
31909115,39,300,880662.0,100,28,845,0903,00NS,0053

In [24]:
FCDFPropostaDPPQ2 = FCDFPropostaDPP2.loc[['31900302', '31900304'], ['Id_PropostaSetorial', 'pps_Quantidade', 'pps_Valor' ]].assign(Fonte='100', Função = '28', SubFunção = '845', Programa = '0903', Ação = '00Q2', Subtítulo = '0053')

In [25]:
FCDFPropostaDPPQ2

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
cad_FCDFDespesaDetalhada,,,,,,,,,
31900302,11,58704,288339863.0,100,28,845,0903,00Q2,0053
31900304,12,4892,22056646.0,100,28,845,0903,00Q2,0053

In [26]:
dfPropostaFCDF = [FCDFPropostaDLF2, FCDFPropostaDSAP2, FCDFPropostaDPPNR2, FCDFPropostaDPPRS, FCDFPropostaDPPNS, FCDFPropostaDPPQ2]

In [27]:
dfPropostaFCDFFinal = pd.concat(dfPropostaFCDF)
dfPropostaFCDFFinal

,Id_PropostaSetorial,pps_Quantidade,pps_Valor,Fonte,Função,SubFunção,Programa,Ação,Subtítulo
CCS,116,12,20000.0,100,28,845,0903,00NR,0053
CCS,117,6,20000.0,100,28,845,0903,00NR,0053
CCS,118,12,20000.0,100,28,845,0903,00NR,0053
CCS,119,1,150000.0,100,28,845,0903,00NR,0053
CCS,120,1,50000.0,100,28,845,0903,00NR,0053
...,...,...,...,...,...,...,...,...,...
31900123,7,126648,5400089.0,100,28,845,0903,00NS,0053
31900126,8,10554,95281452.0,100,28,845,0903,00NS,0053
31909115,39,300,880662.0,100,28,845,0903,00NS,0053
31900302,11,58704,288339863.0,100,28,845,0903,00Q2,0053
31900304,12,4892,22056646.0,100,28,845,0903,00Q2,0053

In [28]:
#Agora transformar o DataFrame em uma lista para ser inserido no MYSQL
list_Proposta = dfPropostaFCDFFinal.values.tolist()
Proposta = []
#Transformando dados 'int' em string'
for lista in list_Proposta:
    linha = []
    for registro in lista:
        registro = str(registro)
        linha.append(registro)
    Proposta.append(linha)
print(Proposta)

[['116', '12', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['117', '6', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['118', '12', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['119', '1', '150000.0', '100', '28', '845', '0903', '00NR', '0053'], ['120', '1', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['121', '12', '900000.0', '100', '28', '845', '0903', '00NR', '0053'], ['122', '1', '180000.0', '100', '28', '845', '0903', '00NR', '0053'], ['242', '0', '11000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['243', '0', '1000.0', '100', '28', '845', '0903', '00NR', '0053'], ['244', '0', '1000.0', '100', '28', '845', '0903', '00NR', '0053'], ['245', '0', '9000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['246', '0', '5000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['247', '0', '700000.0', '100', '28', '845', '0903', '00NR', '0053'], ['248', '0', '700000.0', '100', '28', '845', '0903', '00NR', '0053'], ['249', '0', '2000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['250', '0', '500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['251', '0', '1500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['252', '0', '300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['253', '0', '300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['254', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['255', '0', '300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['256', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['195', '0', '3400.0', '100', '28', '845', '0903', '00NR', '0053'], ['196', '0', '2340.0', '100', '28', '845', '0903', '00NR', '0053'], ['198', '0', '1150.0', '100', '28', '845', '0903', '00NR', '0053'], ['199', '0', '430.0', '100', '28', '845', '0903', '00NR', '0053'], ['200', '0', '640.0', '100', '28', '845', '0903', '00NR', '0053'], ['201', '0', '980.0', '100', '28', '845', '0903', '00NR', '0053'], ['203', '0', '2394.0', '100', '28', '845', '0903', '00NR', '0053'], ['204', '0', '6468.0', '100', '28', '845', '0903', '00NR', '0053'], ['205', '0', '9918.0', '100', '28', '845', '0903', '00NR', '0053'], ['206', '0', '2000.0', '100', '28', '845', '0903', '00NR', '0053'], ['236', '0', '763.0', '100', '28', '845', '0903', '00NR', '0053'], ['237', '0', '3466.0', '100', '28', '845', '0903', '00NR', '0053'], ['239', '0', '900.0', '100', '28', '845', '0903', '00NR', '0053'], ['279', '92', '4000.0', '100', '28', '845', '0903', '00NR', '0053'], ['280', '0', '4000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['281', '28590', '80000.0', '100', '28', '845', '0903', '00NR', '0053'], ['282', '2937', '0.0', '100', '28', '845', '0903', '00NR', '0053'], ['283', '473150', '150000.0', '100', '28', '845', '0903', '00NR', '0053'], ['284', '20000', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['285', '5200', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['286', '57610', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['287', '17400', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['288', '18585', '30000.0', '100', '28', '845', '0903', '00NR', '0053'], ['289', '0', '1400000.0', '100', '28', '845', '0903', '00NR', '0053'], ['290', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['291', '8468', '10000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['292', '2500', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['293', '17700', '165000.0', '100', '28', '845', '0903', '00NR', '0053'], ['294', '9500', '30000.0', '100', '28', '845', '0903', '00NR', '0053'], ['295', '0', '150000.0', '100', '28', '845', '0903', '00NR', '0053'], ['296', '7', '2900000.0', '100', '28', '845', '0903', '00NR', '0053'], ['297', '0', '10000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['298', '0', '650000.0', '100', '28', '845', '0903', '00NR', '0053'], ['299', '0', '5000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['300', '0', '5000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['301', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['302', '0', '15485000.0', '100', '28', '845', '0903', '00NR', '0053'], ['303', '0', '22000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['304', '1690', '30000.0', '100', '28', '845', '0903', '00NR', '0053'], ['305', '1240', '2000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['306', '200', '800000.0', '100', '28', '845', '0903', '00NR', '0053'], ['307', '52', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['308', '0', '4000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['309', '700', '150000.0', '100', '28', '845', '0903', '00NR', '0053'], ['310', '0', '15000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['317', '0', '100000.0', '100', '28', '845', '0903', '00NR', '0053'], ['208', '0', '15000.0', '100', '28', '845', '0903', '00NR', '0053'], ['209', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['210', '0', '10000.0', '100', '28', '845', '0903', '00NR', '0053'], ['211', '0', '2541.0', '100', '28', '845', '0903', '00NR', '0053'], ['212', '0', '10000.0', '100', '28', '845', '0903', '00NR', '0053'], ['213', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['214', '0', '100000.0', '100', '28', '845', '0903', '00NR', '0053'], ['215', '1', '7900000.0', '100', '28', '845', '0903', '00NR', '0053'], ['216', '2162', '1982128.0', '100', '28', '845', '0903', '00NR', '0053'], ['217', '0', '3488142.0', '100', '28', '845', '0903', '00NR', '0053'], ['218', '0', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['219', '0', '0.0', '100', '28', '845', '0903', '00NR', '0053'], ['220', '0', '0.0', '100', '28', '845', '0903', '00NR', '0053'], ['221', '40', '278475.0', '100', '28', '845', '0903', '00NR', '0053'], ['222', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['223', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['224', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['225', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['226', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['227', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['228', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['229', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['230', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['231', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['232', '0', '5000.0', '100', '28', '845', '0903', '00NR', '0053'], ['233', '0', '500.0', '100', '28', '845', '0903', '00NR', '0053'], ['234', '0', '1560.0', '100', '28', '845', '0903', '00NR', '0053'], ['235', '0', '2000.0', '100', '28', '845', '0903', '00NR', '0053'], ['238', '0', '39040.0', '100', '28', '845', '0903', '00NR', '0053'], ['240', '0', '8980.0', '100', '28', '845', '0903', '00NR', '0053'], ['241', '0', '798.0', '100', '28', '845', '0903', '00NR', '0053'], ['125', '1', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['126', '1', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['127', '1', '500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['257', '1', '2500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['258', '1', '1500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['259', '1', '300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['260', '1', '400000.0', '100', '28', '845', '0903', '00NR', '0053'], ['261', '312', '1300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['262', '2', '117600.0', '100', '28', '845', '0903', '00NR', '0053'], ['263', '15', '35952.0', '100', '28', '845', '0903', '00NR', '0053'], ['264', '10', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['265', '10', '2500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['266', '1', '2500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['267', '1213', '2000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['268', '1', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['269', '1', '5000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['270', '1', '3000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['271', '8', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['272', '1', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['273', '1', '500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['274', '1', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['275', '1', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['276', '1', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['277', '1', '450000.0', '100', '28', '845', '0903', '00NR', '0053'], ['278', '1', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['123', '1', '30000.0', '100', '28', '845', '0903', '00NR', '0053'], ['124', '1', '507421.0', '100', '28', '845', '0903', '00NR', '0053'], ['128', '4', '3000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['129', '167', '10000.0', '100', '28', '845', '0903', '00NR', '0053'], ['130', '0', '650000.0', '100', '28', '845', '0903', '00NR', '0053'], ['131', '0', '600000.0', '100', '28', '845', '0903', '00NR', '0053'], ['132', '0', '1600000.0', '100', '28', '845', '0903', '00NR', '0053'], ['133', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['134', '0', '1500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['135', '0', '1300000.0', '100', '28', '845', '0903', '00NR', '0053'], ['136', '12', '240000.0', '100', '28', '845', '0903', '00NR', '0053'], ['137', '0', '1000.0', '100', '28', '845', '0903', '00NR', '0053'], ['138', '0', '1000.0', '100', '28', '845', '0903', '00NR', '0053'], ['139', '0', '4000.0', '100', '28', '845', '0903', '00NR', '0053'], ['140', '0', '1500.0', '100', '28', '845', '0903', '00NR', '0053'], ['141', '0', '4000.0', '100', '28', '845', '0903', '00NR', '0053'], ['142', '0', '2000.0', '100', '28', '845', '0903', '00NR', '0053'], ['143', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['144', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['145', '0', '30000.0', '100', '28', '845', '0903', '00NR', '0053'], ['146', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['147', '0', '20000.0', '100', '28', '845', '0903', '00NR', '0053'], ['148', '0', '184003.0', '100', '28', '845', '0903', '00NR', '0053'], ['149', '0', '184003.0', '100', '28', '845', '0903', '00NR', '0053'], ['150', '0', '500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['151', '0', '6500000.0', '100', '28', '845', '0903', '00NR', '0053'], ['152', '0', '14150.0', '100', '28', '845', '0903', '00NR', '0053'], ['153', '0', '124950.0', '100', '28', '845', '0903', '00NR', '0053'], ['154', '0', '614242.0', '100', '28', '845', '0903', '00NR', '0053'], ['155', '0', '31900.0', '100', '28', '845', '0903', '00NR', '0053'], ['156', '0', '3000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['157', '0', '18900.0', '100', '28', '845', '0903', '00NR', '0053'], ['158', '0', '1200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['159', '0', '4000.0', '100', '28', '845', '0903', '00NR', '0053'], ['160', '0', '10000.0', '100', '28', '845', '0903', '00NR', '0053'], ['161', '0', '100000.0', '100', '28', '845', '0903', '00NR', '0053'], ['162', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['163', '0', '1000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['164', '0', '2000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['165', '0', '40000.0', '100', '28', '845', '0903', '00NR', '0053'], ['166', '0', '15000.0', '100', '28', '845', '0903', '00NR', '0053'], ['167', '0', '40000.0', '100', '28', '845', '0903', '00NR', '0053'], ['168', '0', '200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['169', '0', '100000.0', '100', '28', '845', '0903', '00NR', '0053'], ['170', '0', '337333.0', '100', '28', '845', '0903', '00NR', '0053'], ['171', '0', '2225818.0', '100', '28', '845', '0903', '00NR', '0053'], ['172', '0', '2225818.0', '100', '28', '845', '0903', '00NR', '0053'], ['173', '0', '279626.0', '100', '28', '845', '0903', '00NR', '0053'], ['174', '0', '254880.0', '100', '28', '845', '0903', '00NR', '0053'], ['175', '0', '45978.0', '100', '28', '845', '0903', '00NR', '0053'], ['176', '0', '178856.0', '100', '28', '845', '0903', '00NR', '0053'], ['177', '0', '5415.0', '100', '28', '845', '0903', '00NR', '0053'], ['178', '0', '6786.0', '100', '28', '845', '0903', '00NR', '0053'], ['179', '0', '49787.0', '100', '28', '845', '0903', '00NR', '0053'], ['180', '0', '49787.0', '100', '28', '845', '0903', '00NR', '0053'], ['181', '0', '5940.0', '100', '28', '845', '0903', '00NR', '0053'], ['182', '0', '54740.0', '100', '28', '845', '0903', '00NR', '0053'], ['183', '0', '1666.0', '100', '28', '845', '0903', '00NR', '0053'], ['184', '0', '481000.0', '100', '28', '845', '0903', '00NR', '0053'], ['185', '0', '18547.0', '100', '28', '845', '0903', '00NR', '0053'], ['186', '0', '7892.0', '100', '28', '845', '0903', '00NR', '0053'], ['187', '0', '1893.0', '100', '28', '845', '0903', '00NR', '0053'], ['188', '0', '78825.0', '100', '28', '845', '0903', '00NR', '0053'], ['189', '0', '164218.0', '100', '28', '845', '0903', '00NR', '0053'], ['190', '0', '210000.0', '100', '28', '845', '0903', '00NR', '0053'], ['191', '0', '264000.0', '100', '28', '845', '0903', '00NR', '0053'], ['192', '0', '50000.0', '100', '28', '845', '0903', '00NR', '0053'], ['193', '0', '40000.0', '100', '28', '845', '0903', '00NR', '0053'], ['194', '0', '1200000.0', '100', '28', '845', '0903', '00NR', '0053'], ['197', '6', '14000.0', '100', '28', '845', '0903', '00NR', '0053'], ['202', '0', '900000.0', '100', '28', '845', '0903', '00NR', '0053'], ['207', '0', '900000.0', '100', '28', '845', '0903', '00NR', '0053'], ['57', '0', '650000.0', '100', '28', '845', '0903', '00FM', '0053'], ['59', '0', '893584.0', '100', '28', '845', '0903', '00FM', '0053'], ['60', '0', '115000.0', '100', '28', '845', '0903', '00FM', '0053'], ['61', '0', '12000.0', '100', '28', '845', '0903', '00FM', '0053'], ['62', '0', '920000.0', '100', '28', '845', '0903', '00FM', '0053'], ['63', '0', '2233626.0', '100', '28', '845', '0903', '00FM', '0053'], ['65', '0', '80000.0', '100', '28', '845', '0903', '00FM', '0053'], ['66', '0', '60000.0', '100', '28', '845', '0903', '00FM', '0053'], ['67', '0', '60000.0', '100', '28', '845', '0903', '00FM', '0053'], ['68', '0', '60000.0', '100', '28', '845', '0903', '00FM', '0053'], ['69', '0', '30000.0', '100', '28', '845', '0903', '00FM', '0053'], ['70', '0', '11000000.0', '100', '28', '845', '0903', '00FM', '0053'], ['71', '0', '1905194.0', '100', '28', '845', '0903', '00FM', '0053'], ['72', '0', '148000000.0', '100', '28', '845', '0903', '00FM', '0053'], ['73', '0', '9153000.0', '100', '28', '845', '0903', '00FM', '0053'], ['74', '0', '510000.0', '100', '28', '845', '0903', '00FM', '0053'], ['75', '0', '31345038.0', '100', '28', '845', '0903', '00FM', '0053'], ['76', '0', '42300000.0', '100', '28', '845', '0903', '00FM', '0053'], ['77', '0', '6340000.0', '100', '28', '845', '0903', '00FM', '0053'], ['78', '0', '23526036.0', '100', '28', '845', '0903', '00FM', '0053'], ['79', '0', '3171802.0', '100', '28', '845', '0903', '00FM', '0053'], ['80', '0', '23970.0', '100', '28', '845', '0903', '00FM', '0053'], ['81', '0', '79882.0', '100', '28', '845', '0903', '00FM', '0053'], ['82', '0', '6041804.0', '100', '28', '845', '0903', '00FM', '0053'], ['83', '0', '30000.0', '100', '28', '845', '0903', '00FM', '0053'], ['84', '0', '85000.0', '100', '28', '845', '0903', '00FM', '0053'], ['85', '0', '30000.0', '100', '28', '845', '0903', '00FM', '0053'], ['86', '0', '66343.0', '100', '28', '845', '0903', '00FM', '0053'], ['88', '0', '45000.0', '100', '28', '845', '0903', '00FM', '0053'], ['89', '0', '10000000.0', '100', '28', '845', '0903', '00FM', '0053'], ['90', '0', '2100000.0', '100', '28', '845', '0903', '00FM', '0053'], ['92', '0', '71343.0', '100', '28', '845', '0903', '00FM', '0053'], ['93', '0', '1000093.0', '100', '28', '845', '0903', '00FM', '0053'], ['94', '0', '24398.0', '100', '28', '845', '0903', '00FM', '0053'], ['95', '0', '3536353.0', '100', '28', '845', '0903', '00FM', '0053'], ['96', '0', '553109.0', '100', '28', '845', '0903', '00FM', '0053'], ['97', '0', '2352761.0', '100', '28', '845', '0903', '00FM', '0053'], ['98', '0', '2115556.0', '100', '28', '845', '0903', '00FM', '0053'], ['99', '0', '22350.0', '100', '28', '845', '0903', '00FM', '0053'], ['100', '0', '144000000.0', '100', '28', '845', '0903', '00FM', '0053'], ['101', '0', '16631.0', '100', '28', '845', '0903', '00FM', '0053'], ['103', '0', '60000.0', '100', '28', '845', '0903', '00FM', '0053'], ['104', '0', '98500.0', '100', '28', '845', '0903', '00FM', '0053'], ['105', '0', '526879.0', '100', '28', '845', '0903', '00FM', '0053'], ['106', '0', '40000.0', '100', '28', '845', '0903', '00FM', '0053'], ['107', '0', '123404.0', '100', '28', '845', '0903', '00FM', '0053'], ['108', '0', '231054.0', '100', '28', '845', '0903', '00FM', '0053'], ['109', '0', '160600.0', '100', '28', '845', '0903', '00FM', '0053'], ['110', '0', '160600.0', '100', '28', '845', '0903', '00FM', '0053'], ['111', '0', '250000.0', '100', '28', '845', '0903', '00FM', '0053'], ['112', '0', '12960.0', '100', '28', '845', '0903', '00FM', '0053'], ['311', '0', '253328680.0', '100', '28', '845', '0903', '00FM', '0053'], ['312', '0', '6138147.0', '100', '28', '845', '0903', '00FM', '0053'], ['313', '0', '1200000.0', '100', '28', '845', '0903', '00FM', '0053'], ['314', '0', '3970000.0', '100', '28', '845', '0903', '00FM', '0053'], ['58', '0', '400000.0', '100', '28', '845', '0903', '00FM', '0053'], ['64', '0', '70000.0', '100', '28', '845', '0903', '00FM', '0053'], ['87', '0', '25000.0', '100', '28', '845', '0903', '00FM', '0053'], ['91', '0', '10475935.0', '100', '28', '845', '0903', '00FM', '0053'], ['102', '0', '281000.0', '100', '28', '845', '0903', '00FM', '0053'], ['113', '0', '1800000.0', '100', '28', '845', '0903', '00FM', '0053'], ['114', '0', '115000.0', '100', '28', '845', '0903', '00FM', '0053'], ['115', '0', '65000.0', '100', '28', '845', '0903', '00FM', '0053'], ['315', '0', '501200.0', '100', '28', '845', '0903', '00FM', '0053'], ['316', '0', '2421586.0', '100', '28', '845', '0903', '00FM', '0053'], ['46', '1800', '450000.0', '100', '28', '845', '0903', '00NR', '0053'], ['48', '900', '350000.0', '100', '28', '845', '0903', '00NR', '0053'], ['49', '12053', '24755223.0', '100', '28', '845', '0903', '00NR', '0053'], ['53', '12', '95062.0', '100', '28', '845', '0903', '00NR', '0053'], ['23', '144636', '230354573.0', '100', '28', '845', '0903', '00NR', '0053'], ['24', '144636', '165917967.0', '100', '28', '845', '0903', '00NR', '0053'], ['25', '144636', '70776531.0', '100', '28', '845', '0903', '00NR', '0053'], ['26', '144636', '1671914.0', '100', '28', '845', '0903', '00NR', '0053'], ['28', '144636', '152517596.0', '100', '28', '845', '0903', '00NR', '0053'], ['30', '144636', '527653219.0', '100', '28', '845', '0903', '00NR', '0053'], ['34', '12053', '89365604.0', '100', '28', '845', '0903', '00NR', '0053'], ['35', '12053', '29318756.0', '100', '28', '845', '0903', '00NR', '0053'], ['36', '144636', '15460731.0', '100', '28', '845', '0903', '00NR', '0053'], ['38', '12', '1413.0', '100', '28', '845', '0903', '00NR', '0053'], ['40', '2300', '110000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['29', '300000', '120000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['33', '3800', '30000000.0', '100', '28', '845', '0903', '00NR', '0053'], ['54', '900', '33000000.0', '100', '28', '845', '0903', '00RS', '0053'], ['55', '375', '700000.0', '100', '28', '845', '0903', '00RS', '0053'], ['56', '22607', '433012458.0', '100', '28', '845', '0903', '00RS', '0053'], ['1', '126648', '34843636.0', '100', '28', '845', '0903', '00NS', '0053'], ['3', '126648', '4421741.0', '100', '28', '845', '0903', '00NS', '0053'], ['4', '126648', '446097878.0', '100', '28', '845', '0903', '00NS', '0053'], ['5', '126648', '240697190.0', '100', '28', '845', '0903', '00NS', '0053'], ['6', 

In [29]:
for registro in Proposta:
    engine.execute('SET FOREIGN_KEY_CHECKS=0;')
    engine.execute('INSERT INTO tbl_FCDFProposta ( prf_PropostaSetorial, prf_Quantidade, prf_Valor, prf_Fonte, prf_Funcao, prf_Subfuncao, prf_Programa, prf_Acao, prf_Subtitulo) values ("'+registro[0]+'","'+registro[1]+'","'+registro[2]+'","'+registro[3]+'","'+registro[4]+'","'+registro[5]+'","'+registro[6]+'","'+registro[7]+'","'+registro[8]+'");')